name: "Config Change Notifier"
description: "Detects changes in config files and notifies via PR comment and/or Slack"
inputs:
  config_files:
    description: "List of config files to monitor"
    required: true
  language:
    description: "Notification language (en or ja)"
    required: false
    default: "en"
  notification_method:
    description: "Notification method (pr_comment, slack, or both)"
    required: false
    default: "pr_comment"
  slack_webhook:
    description: "Slack webhook URL for notifications"
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Check config changes and notify
      id: check_changes
      run: python ${{ github.action_path }}/scripts/check_config_changes.py
      env:
        CONFIG_FILES: ${{ inputs.config_files }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ github.token }}
        LANGUAGE: ${{ inputs.language }}
        NOTIFICATION_METHOD: ${{ inputs.notification_method }}
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
      shell: bash