name: "Config Change Notifier"
description: "Detects changes in config files and adds ChangeRequired reviews"
inputs:
  config_files:
    description: "List of config files to monitor"
    required: true
  language:
    description: "Notification language (en or ja)"
    required: false
    default: "en"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: pip install requests
      shell: bash
    - name: Check config changes and add reviews
      id: check_changes
      run: python ${{ github.action_path }}/scripts/check_config_changes.py
      env:
        CONFIG_FILES: ${{ inputs.config_files }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ github.token }}
        LANGUAGE: ${{ inputs.language }}
      shell: bash
